name: mlos_python_environment
depencendies:
  - bayesian-optimization=1.0.1
  - scikit-learn=0.22.1
  - scipy=1.3.2
  - numpy=1.8.1
  - pandas=1.0.3
  - pylint=2.3.1
  - pyobdc=4.0.30
  - grpcio-tools=1.30.0
  - pip
  - jupyterlab
  - jupyter
  - ipykernel
  - matplotlib
  - seaborn